version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Build complete. No compilation needed for Python.
  post_build:
    commands:
      - echo Build successful. Preparing for deploy...

artifacts:
  files:
    - app.py
    - requirements.txt
    - appspec.yml
    - scripts/*
